steps:
  - name: Update Composer.
    command: '/usr/local/bin/composer self-update'
  - name: Generate Drupal 8 files.
    command: 'composer create-project zivtech/bear-project:8.2.x-dev bear8'
  - name: Probo site setup
    plugin: Drupal
    clearCaches: false
    subDirectory: bear8/docroot
    settingsRequireFile: site-settings.php
    drupalVersion: 8
    configSyncDirectory: config/sync
  - name: Run install
    command: "drush site-install --root=/var/www/html/bear8/docroot bear --db-url='mysqli://root:strongpassword@localhost/bear'"
